apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: htalukder-deployer-watson-nlp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: htalukder-deployer
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/htalukder-deployer/watson-nlp
    repoURL: https://github.com/htalukderibm/gitops-repo
    targetRevision: main
    helm:
      releaseName: watson-nlp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
