apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: htalukder-deployer-ubi-helm
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: htalukder-deployer
    server: https://kubernetes.default.svc
  project: 3-applications
  source:
    path: payload/3-applications/namespace/htalukder-deployer/ubi-helm
    repoURL: https://github.com/htalukderibm/gitops-repo
    targetRevision: main
    helm:
      releaseName: ubi-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
