apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: htalukder-deployer-ibm-entitlement-key
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: htalukder-deployer
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/htalukder-deployer/ibm-entitlement-key
    repoURL: https://github.com/htalukderibm/gitops-repo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
